DROP TABLE IF EXISTS books;

CREATE TABLE BOOKS (
  ID INTEGER NOT NULL AUTO_INCREMENT, 
  NAME VARCHAR(250) NOT NULL,
  AUTHOR VARCHAR(250) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  COST FLOAT NOT NULL,
  ISBN VARCHAR(250) NOT NULL,
  COVER_IMAGE VARCHAR(250) NOT NULL,
  CREATE_AT DATE NOT NULL,
  UPDATE_AT DATE NOT NULL,
  PRIMARY KEY(ID)
);